#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Add icons of general interest
#
/control/execute ./macros/icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Run menu :
/gui/addMenu run Run
/gui/addButton run run.mac "/control/execute ./macros/run.mac"
#


# Projection menu :
/gui/addMenu projection Projection
/gui/addButton projection "view from y+" "/control/execute ./macros/projy+.mac"
/gui/addButton projection "view from y-" "/control/execute ./macros/projy-.mac"
/gui/addButton projection "view from z+" "/control/execute ./macros/projz+.mac"
/gui/addButton projection "view from z-" "/control/execute ./macros/projz-.mac"
/gui/addButton projection "view from x+" "/control/execute ./macros/projx+.mac"
/gui/addButton projection "view from x-" "/control/execute ./macros/projx-.mac"

# Cut menu :
/gui/addMenu cut Cut
/gui/addButton cut "cut x=  0 m" "/control/execute ./macros/cutx0.mac"
/gui/addButton cut "cut y=  0 m" "/control/execute ./macros/cuty0.mac"
/gui/addButton cut "cut z=  0 m" "/control/execute ./macros/cutz0.mac"

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#

