/vis/open OGLIX 600x600-0+0
#/vis/open HepRepFile
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/background  1 1 1
/vis/viewer/set/viewpointVector 0 1 0
/vis/viewer/set/upVector 0 0 -1
/vis/viewer/zoomTo 1
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- black
/vis/modeling/trajectories/drawByParticleID-0/set e+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set gamma green
/vis/modeling/trajectories/drawByParticleID-0/set alpha blue
/vis/modeling/trajectories/drawByParticleID-0/set Li7 red

#/vis/modeling/trajectories/create/drawByAttribute
#/vis/modeling/trajectories/drawByAttribute-0/addValue pai_key PAIModel
#/vis/modeling/trajectories/drawByAttribute-0/pai_key/setLineColour   red


/vis/scene/add/hits


/vis/scene/endOfEventAction accumulate
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#/control/execute ./macros/gui.mac
