# Macro file for the 
# initialization of G4GeneralParticleSource
# to be used together with "task2b.c"
#
#
/gps/energy 2. GeV
/gps/position 0. 0. 0. m
/gps/direction 0. 0. 1.
#
# Gauss distribution in position
/gps/pos/type Beam
/gps/pos/sigma_x 0.1 mm
/gps/pos/sigma_y 0.1 mm

#
# Gauss distribution in angle 
/gps/ang/type beam2d
/gps/ang/sigma_x 0.1 mrad
/gps/ang/sigma_y 0.1 mrad
/gps/ang/rot1 -1. 0. 0.
#
/run/beamOn 50

